### PR TITLE
Display images from api

### PR DESCRIPTION
**Pull request by dorianeGH**

### CODE REVIEW

**Comment by dorianeGH** [comment]
No connected issue for this task

**Story**
As a user I want to have see Sensors Map and rainMap when I select the related timestamp & location

**Criteria & special considerations**
create a RainMap component
experiment useState to be placed in Context, since it will be reused in AssimilationPage
get path of the images from DB using ExperimentModel and location route

**Test**
To test this issue, you need to have an image in storage folder

**Review by So-G — DISMISSED** [review]
good job !

**Review by So-G — APPROVED** [review]
alright! solved conflict in location.js to account for new experiment model
placeholder "rainmap" and sensors appear on history page when selecting an experiment in our DB!

**Review by hkamalo — APPROVED** [review]
Quick change on Experiment model create conflict with, location/sensors (with timestamp) call. now it's ok good to merge

**Pull request merged**
